# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='comments.Article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='arXiv_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
